name: Test & Coverage
on: pull_request

jobs:
  test:
    strategy:
      matrix:
        # Test if using native json or pyjson5 for json parsing
        os: ['ubuntu-latest', 'windows-latest']
        python: ['3.7', '3.9']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage

      - name: Build coverage file
        # Run pytest and generate a .coverage.[...] report file for the current
        # matrix. This filename won't conflict with the other matrix reports
        run: |
          coverage run -m pytest

      - name: Upload coverage
        # Upload the current .coverage.[...] file to the coverage artifact.
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage.*
          retention-days: 1

  coverage:
    # Only allow this job to run once all of the test jobs finish
    needs: test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Download coverage artifacts
        # Download all of the coverage artifacts generated by all of the test jobs
        uses: actions/download-artifact@v3
        with:
          name: coverage

      # Tox runs `coverage combine` and `coverage xml`
      - name: Combine coverage and report
        # Combine all of the .coverage.[...] files into the .coverage file.
        # Then generate the report and save it as the coverage.xml file.
        run: |
          coverage combine
          coverage report
          coverage xml

      - name: Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
